name: continous-build
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: | 
           hostname
      - name: my step2
        run: |
          echo "$greetings from $name"
          sleep 10
      - run: |
          echo "hello from step3"
          sleep 10
      - name: my step4 for testing multiple lines of code execution
        run: |
          echo "hello from step4"
          sleep 10
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step1
        run: | 
           hostname
      - name: my step2
        run: |
          echo "hello from step2"
          sleep 10
      
  deploy: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: step1
        run: | 
           hostname
      - name: my step2
        run: |
          echo "hello from step2"
          sleep 10
      
  notification-start: 
    runs-on: ubuntu-latest
    steps:
      - name: my step1
        run: |
          echo "Job started"
          sleep 10
